# Generated by Django 3.2.9 on 2022-04-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(height_field=100, upload_to='portfolio/images/'),
        ),
    ]
